# Generated by Django 5.0.3 on 2024-03-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('image_profile', models.ImageField(blank=True, upload_to='image_profile', verbose_name='Imagen de perfil')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('T', 'Transgenero'), ('O', 'Otro')], max_length=1, verbose_name='Genero')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=3, verbose_name='Altura')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=3, verbose_name='Peso')),
                ('chest', models.DecimalField(blank=True, decimal_places=2, max_digits=3, verbose_name='Pecho')),
                ('arms', models.DecimalField(blank=True, decimal_places=2, max_digits=3, verbose_name='Brazos')),
                ('waist', models.DecimalField(blank=True, decimal_places=2, max_digits=3, verbose_name='cintura')),
                ('legs', models.DecimalField(blank=True, decimal_places=2, max_digits=3, verbose_name='Piernas')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
