# Generated by Django 5.0.3 on 2024-03-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='arms',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Brazos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='chest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Pecho'),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='user',
            name='legs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Piernas'),
        ),
        migrations.AlterField(
            model_name='user',
            name='waist',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='cintura'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Peso'),
        ),
    ]
