# Generated by Django 5.0.3 on 2024-03-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_arms_alter_user_chest_alter_user_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_register',
            field=models.CharField(blank=True, max_length=6, verbose_name='Codigo de Registro'),
        ),
    ]
