# Generated by Django 5.0.3 on 2024-03-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Peso')),
                ('chest', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Pecho')),
                ('arms', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Brazos')),
                ('weist', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Cintura')),
                ('legs', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Piernas')),
            ],
            options={
                'verbose_name': 'Control',
                'verbose_name_plural': 'Controles',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.CharField(max_length=100, verbose_name='Ejercicio')),
                ('description', models.TextField(verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
            },
        ),
        migrations.CreateModel(
            name='ExerciseRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Peso')),
                ('repetition', models.IntegerField(verbose_name='Repeticiones')),
            ],
            options={
                'verbose_name': 'Registro de ejercicio',
                'verbose_name_plural': 'Registro de ejercicios',
            },
        ),
    ]
